### ISSUE TITLE
Constant is still named pros instead of vexide and affects docs link

### ISSUE THREAD

**Issue by mrtomblue** [vexide/website#4]
## Problem Description
When you hover or click on the API Documentation button on the home page the link is [`docs.rs/pros`](https://docs.rs/pros) instead of [`docs.rs/vexide`](https://docs.rs/vexide). The actual "typo" seems to be the variable in `constants.ts` which is used in `index.astro`

 https://github.com/vexide/website/blob/acaf65b2a7bb1905be0fd5fb4527bf88cf847850/src/constants.ts#L1 

 https://github.com/vexide/website/blob/acaf65b2a7bb1905be0fd5fb4527bf88cf847850/src/pages/index.astro#L39

**Comment by zabackary** [comment]
@Tropix126 @Gavin-Niederman This can be closed.
